#!/bin/bash
# Agent Identity Plugin Setup Script
# Configures your system to spawn Claude agents with isolated Cortex identities

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================"
echo "Agent Identity Plugin Setup"
echo "========================================"
echo

# Get current user info
CALLING_USER=$(whoami)
CALLING_GROUP=$(id -gn)
CLAUDE_PATH=$(which claude 2>/dev/null || echo "$HOME/.local/bin/claude")
SUDOERS_FILE="/etc/sudoers.d/claude-agents"

echo "Detected configuration:"
echo "  User: $CALLING_USER"
echo "  Group: $CALLING_GROUP"
echo "  Claude: $CLAUDE_PATH"
echo

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${RED}Error: Don't run this script as root. Run as your normal user.${NC}"
    exit 1
fi

# Check if claude exists
if [ ! -f "$CLAUDE_PATH" ]; then
    echo -e "${RED}Error: Claude not found at $CLAUDE_PATH${NC}"
    echo "Install Claude Code first: https://claude.ai/code"
    exit 1
fi

# Step 1: Create agent user
echo "========================================"
echo "Step 1: Create Agent User"
echo "========================================"
echo
read -p "Agent username (e.g., agent-cortexd-tester): " AGENT_USER

if [ -z "$AGENT_USER" ]; then
    echo -e "${RED}Error: Agent username required${NC}"
    exit 1
fi

if ! [[ "$AGENT_USER" =~ ^agent- ]]; then
    echo -e "${YELLOW}Warning: Agent names should start with 'agent-' by convention${NC}"
    read -p "Continue anyway? (y/n): " CONTINUE
    if [ "$CONTINUE" != "y" ]; then
        exit 1
    fi
fi

if id "$AGENT_USER" &>/dev/null; then
    echo -e "${GREEN}Agent user '$AGENT_USER' already exists${NC}"
    # Ensure they're in the right group
    if ! id "$AGENT_USER" | grep -q "$CALLING_GROUP"; then
        echo "Adding to group '$CALLING_GROUP'..."
        sudo usermod -aG "$CALLING_GROUP" "$AGENT_USER"
    fi
else
    echo "Creating agent user '$AGENT_USER' with group '$CALLING_GROUP'..."
    sudo useradd -r -s /usr/sbin/nologin -G "$CALLING_GROUP" "$AGENT_USER"
    echo -e "${GREEN}Created agent user '$AGENT_USER'${NC}"
fi

# Get agent UID
AGENT_UID=$(id -u "$AGENT_USER")
echo "  UID: $AGENT_UID"
echo

# Step 2: Configure sudoers
echo "========================================"
echo "Step 2: Configure Sudoers"
echo "========================================"
echo

# Build sudoers content
SUDOERS_CONTENT="# Agent Identity Plugin - Claude Code agent spawning
# Generated by setup.sh on $(date)

# Agent users alias - add new agents here
Runas_Alias AGENTS = $AGENT_USER

# Allow $CALLING_USER to run commands as agent users without password
$CALLING_USER ALL=(AGENTS) NOPASSWD: ALL
"

# Check if sudoers file exists and has content
if [ -f "$SUDOERS_FILE" ]; then
    echo "Existing sudoers file found. Current content:"
    sudo cat "$SUDOERS_FILE"
    echo
    echo "Adding new agent to AGENTS alias..."

    # Check if AGENTS alias exists and add to it
    if sudo grep -q "^Runas_Alias AGENTS" "$SUDOERS_FILE"; then
        # Add to existing alias
        sudo sed -i "s/^Runas_Alias AGENTS = \(.*\)/Runas_Alias AGENTS = \1, $AGENT_USER/" "$SUDOERS_FILE"
    else
        # Create alias and rule
        APPEND_CONTENT="
# Agent: $AGENT_USER (added $(date))
Runas_Alias AGENTS = $AGENT_USER
$CALLING_USER ALL=(AGENTS) NOPASSWD: ALL"
        echo "$APPEND_CONTENT" | sudo tee -a "$SUDOERS_FILE" > /dev/null
    fi
else
    echo "Creating sudoers file..."
    echo "$SUDOERS_CONTENT" | sudo tee "$SUDOERS_FILE" > /dev/null
fi

sudo chmod 440 "$SUDOERS_FILE"
echo -e "${GREEN}Sudoers configured${NC}"

# Verify sudoers syntax
if sudo visudo -c -f "$SUDOERS_FILE" 2>/dev/null; then
    echo -e "${GREEN}Sudoers syntax OK${NC}"
else
    echo -e "${RED}Error: Sudoers syntax error. Please fix manually.${NC}"
    exit 1
fi
echo

# Step 3: Configure Claude credentials access
echo "========================================"
echo "Step 3: Configure Claude Credentials"
echo "========================================"
echo
CLAUDE_CONFIG="$HOME/.claude"
CREDENTIALS_FILE="$CLAUDE_CONFIG/.credentials.json"

if [ ! -f "$CREDENTIALS_FILE" ]; then
    echo -e "${YELLOW}Warning: Claude credentials not found at $CREDENTIALS_FILE${NC}"
    echo "Make sure you're logged into Claude Code first."
else
    echo "Making Claude config group-readable..."
    chmod g+x "$CLAUDE_CONFIG"
    chmod g+r "$CREDENTIALS_FILE"
    echo -e "${GREEN}Credentials configured${NC}"
fi
echo

# Step 4: Make Claude binary accessible
echo "========================================"
echo "Step 4: Configure Claude Binary Access"
echo "========================================"
echo
echo "Making Claude path group-traversable..."

# Resolve symlinks to find actual path
CLAUDE_REAL=$(readlink -f "$CLAUDE_PATH" 2>/dev/null || echo "$CLAUDE_PATH")
CLAUDE_DIR=$(dirname "$CLAUDE_REAL")

# Make home and relevant directories traversable
chmod g+x "$HOME" 2>/dev/null || echo "  Note: Couldn't chmod $HOME (may already be set)"
chmod g+x "$HOME/.local" 2>/dev/null || true
chmod g+x "$HOME/.local/bin" 2>/dev/null || true
chmod g+x "$HOME/.local/share" 2>/dev/null || true
chmod g+x "$HOME/.local/share/claude" 2>/dev/null || true
chmod g+x "$HOME/.local/share/claude/versions" 2>/dev/null || true

echo -e "${GREEN}Claude binary accessible${NC}"
echo

# Step 5: Verify setup
echo "========================================"
echo "Step 5: Verify Setup"
echo "========================================"
echo

echo "Testing sudo access..."
if sudo -u "$AGENT_USER" whoami &>/dev/null; then
    echo -e "${GREEN}✓ Sudo works${NC}"
else
    echo -e "${RED}✗ Sudo failed - check sudoers configuration${NC}"
fi

echo "Testing group membership..."
if id "$AGENT_USER" | grep -q "$CALLING_GROUP"; then
    echo -e "${GREEN}✓ Agent in group '$CALLING_GROUP'${NC}"
else
    echo -e "${RED}✗ Agent not in group - may need re-login${NC}"
fi

echo "Testing Claude execution..."
CLAUDE_VERSION=$(sudo -u "$AGENT_USER" sh -c "export HOME=/tmp/$AGENT_USER; mkdir -p \$HOME; $CLAUDE_PATH --version" 2>/dev/null || echo "FAILED")
if [ "$CLAUDE_VERSION" != "FAILED" ]; then
    echo -e "${GREEN}✓ Claude runs as agent ($CLAUDE_VERSION)${NC}"
else
    echo -e "${RED}✗ Claude failed to run - check binary permissions${NC}"
fi
echo

# Summary
echo "========================================"
echo "Setup Complete!"
echo "========================================"
echo
echo "Agent '$AGENT_USER' (UID $AGENT_UID) is ready."
echo
echo "To spawn this agent:"
echo "  /spawn-agent $AGENT_USER \"Your task here\""
echo
echo "To add more agents, run this script again."
echo
echo "Agent Cortex tables will be namespaced as: ${AGENT_UID}:tablename"
echo
